# Generated by Django 5.2.6 on 2025-09-16 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(help_text='e.g., Icarus, Performance Designs', max_length=50)),
                ('model', models.CharField(help_text='e.g., Sabre2, Katana', max_length=50)),
                ('size', models.IntegerField(help_text='Size in square feet')),
                ('year_manufactured', models.IntegerField(blank=True, null=True)),
                ('line_set', models.CharField(blank=True, help_text='Line set type if modified', max_length=50)),
                ('modifications', models.TextField(blank=True, help_text='Any modifications made')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary canopy for this user')),
                ('is_active', models.BooleanField(default=True, help_text='Still in use')),
                ('retired_date', models.DateField(blank=True, null=True)),
                ('retirement_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canopies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Canopies',
                'indexes': [models.Index(fields=['user', 'is_primary'], name='users_canop_user_id_3f6139_idx'), models.Index(fields=['manufacturer', 'model'], name='users_canop_manufac_125363_idx'), models.Index(fields=['size'], name='users_canop_size_6188ee_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_primary_canopy_per_user')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, help_text='Skydiving license number', max_length=20)),
                ('uspa_number', models.CharField(blank=True, help_text='USPA member number', max_length=20)),
                ('license_level', models.CharField(blank=True, choices=[('A', 'A License'), ('B', 'B License'), ('C', 'C License'), ('D', 'D License')], max_length=2)),
                ('coach', models.BooleanField(default=False)),
                ('affi', models.BooleanField(default=False)),
                ('ti', models.BooleanField(default=False)),
                ('total_jumps', models.IntegerField(blank=True, null=True)),
                ('swoop_jumps', models.IntegerField(blank=True, null=True)),
                ('exit_weight', models.FloatField(blank=True, help_text='Exit weight in lbs', null=True)),
                ('home_dz', models.CharField(blank=True, help_text='Home drop zone', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('units', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='imperial', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('public_profile', models.BooleanField(default=False, help_text='Allow others to see your stats')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['license_level'], name='users_userp_license_db1df6_idx'), models.Index(fields=['home_dz'], name='users_userp_home_dz_3959b7_idx'), models.Index(fields=['public_profile'], name='users_userp_public__6d3a04_idx')],
            },
        ),
    ]
