# Generated by Django 5.2.6 on 2025-09-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_public_flights',
            field=models.BooleanField(default=False, help_text='Automatically make all uploaded flights public'),
        ),
    ]
