# Generated by Django 5.2.6 on 2026-03-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_jump_number_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='home_dz',
            field=models.CharField(blank=True, help_text='Home drop zone (legacy text)', max_length=100),
        ),
    ]
