# Generated by Django 5.2.6 on 2026-03-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_home_dz'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='iad_sl',
            field=models.BooleanField(default=False, help_text='IAD / Static Line Instructor rating'),
        ),
    ]
