# Generated by Django 5.2.6 on 2026-03-31 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_uspa_official'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(help_text='e.g., Javelin, Vector, Mirage, Infinity', max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('dom', models.DateField(blank=True, help_text='Date of manufacture', null=True)),
                ('reserve_manufacturer', models.CharField(blank=True, max_length=50)),
                ('reserve_model', models.CharField(blank=True, max_length=50)),
                ('reserve_size', models.IntegerField(blank=True, help_text='Size in square feet', null=True)),
                ('reserve_dom', models.DateField(blank=True, help_text='Reserve date of manufacture', null=True)),
                ('reserve_repack_date', models.DateField(blank=True, help_text='Last reserve repack date (180-day cycle)', null=True)),
                ('aad_manufacturer', models.CharField(blank=True, help_text='e.g., Cypres, VIGIL, MARS', max_length=50)),
                ('aad_serial_number', models.CharField(blank=True, max_length=50)),
                ('aad_service_date', models.DateField(blank=True, help_text='Next AAD service due date', null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
