services:
  - type: web
    name: swoopr
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate
      gunicorn Swoopr.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true

  - type: pserv
    name: swoopr-db
    env: postgresql
    plan: free
    databases:
      - name: swoopr
        user: swoopr