# Generated by Django 5.2.6 on 2026-03-31 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_dropzone_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if waiver does not expire', null=True)),
                ('waiver_version', models.CharField(blank=True, help_text="e.g., '2024-01', 'v3'", max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dropzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='organizations.dropzone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_date'],
            },
        ),
    ]
