# Generated by Django 5.2.6 on 2026-07-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_aircraft_dz_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='climb_rate_fpm',
            field=models.IntegerField(blank=True, help_text='Baseline climb rate in feet/min at a typical load. Used to estimate time-to-altitude before per-day stats exist.', null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='fuel_burn_gph',
            field=models.FloatField(blank=True, help_text='Fuel burn in gallons/hour.', null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='fuel_capacity_gal',
            field=models.FloatField(blank=True, help_text='Usable fuel capacity in gallons.', null=True),
        ),
    ]
