# Generated by Django 5.2.6 on 2026-05-21 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0002_phase3_manifest'),
        ('organizations', '0003_waiver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='add_ons',
            field=models.JSONField(blank=True, default=dict, help_text='e.g. {"video": true, "photos": true}'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='charged_price_cents',
            field=models.IntegerField(blank=True, help_text='Final amount actually charged.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='quoted_price_cents',
            field=models.IntegerField(blank=True, help_text='Price shown to the customer when booking.', null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stub', 'Stub (no-op)'), ('stripe', 'Stripe'), ('square', 'Square'), ('cash', 'Cash')], default='stub', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('voided', 'Voided')], default='pending', max_length=12)),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='dz.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jump_type', models.CharField(choices=[('tandem', 'Tandem'), ('aff', 'AFF'), ('coach', 'Coach Jump')], max_length=10)),
                ('base_price_cents', models.IntegerField(help_text='Default price when no demand tier applies.')),
                ('min_price_cents', models.IntegerField(default=0, help_text='Absolute floor — never charge less.')),
                ('is_active', models.BooleanField(default=True)),
                ('dropzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_configs', to='organizations.dropzone')),
            ],
            options={
                'ordering': ['dropzone', 'jump_type'],
                'unique_together': {('dropzone', 'jump_type')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlotPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "Sunset Jump", "Sunrise Special"', max_length=100)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('surcharge_cents', models.IntegerField(help_text='Added on top of demand-tier price.')),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='Day integers [0=Mon … 6=Sun] this applies to. Empty = every day.')),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='dz.pricingconfig')),
            ],
            options={
                'ordering': ['config', 'time_from'],
            },
        ),
        migrations.CreateModel(
            name='PricingOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_cents', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='dz.pricingconfig')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('config', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_sold', models.IntegerField(help_text='Minimum confirmed+pending bookings on this date to activate this tier.')),
                ('price_cents', models.IntegerField()),
                ('label', models.CharField(blank=True, help_text='e.g. "Early Bird", "Standard", "Peak"', max_length=50)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='dz.pricingconfig')),
            ],
            options={
                'ordering': ['config', 'min_sold'],
                'unique_together': {('config', 'min_sold')},
            },
        ),
    ]
