# Generated by Django 5.2.6 on 2026-07-29 17:47

import django.db.models.deletion
from django.db import migrations, models


def backfill_dropzone(apps, schema_editor):
    """Best-effort: stamp existing stats rows with the aircraft's current DZ."""
    DailyAircraftStats = apps.get_model('dz', 'DailyAircraftStats')
    for stats in DailyAircraftStats.objects.select_related('aircraft').filter(dropzone__isnull=True):
        if stats.aircraft.dropzone_id:
            stats.dropzone_id = stats.aircraft.dropzone_id
            stats.save(update_fields=['dropzone'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_aircraft_performance_fields'),
        ('dz', '0003_pricing_payment'),
        ('organizations', '0003_waiver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyaircraftstats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyaircraftstats',
            name='dropzone',
            field=models.ForeignKey(blank=True, help_text='DZ this day of stats was recorded at. Keeps stats separate when the same aircraft flies at more than one DZ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_aircraft_stats', to='organizations.dropzone'),
        ),
        migrations.AddField(
            model_name='dailyaircraftstats',
            name='rolling_avg_altitude_min',
            field=models.FloatField(blank=True, help_text='Trailing multi-day average minutes from takeoff to exit altitude.', null=True),
        ),
        migrations.AddField(
            model_name='dailyaircraftstats',
            name='rolling_avg_turn_min',
            field=models.FloatField(blank=True, help_text='Trailing multi-day average minutes from landing to next takeoff.', null=True),
        ),
        migrations.AddField(
            model_name='dailyaircraftstats',
            name='sample_jumper_count',
            field=models.IntegerField(blank=True, help_text='Total jumper count across loads sampled for this day.', null=True),
        ),
        migrations.AddField(
            model_name='dailyaircraftstats',
            name='sample_weight_lbs_total',
            field=models.IntegerField(blank=True, help_text='Total jumper weight (lbs) across loads sampled for this day, if known.', null=True),
        ),
        migrations.AddField(
            model_name='jumprunconditions',
            name='hold_called',
            field=models.BooleanField(default=False, help_text='Weather/wind hold currently in effect for this DZ.'),
        ),
        migrations.AddField(
            model_name='jumprunconditions',
            name='wind_speed_kts',
            field=models.IntegerField(blank=True, help_text='Surface wind speed in knots, if known. Used to add a hold buffer to call time estimates in high-wind conditions.', null=True),
        ),
        migrations.RunPython(backfill_dropzone, noop),
        migrations.AlterField(
            model_name='dailyaircraftstats',
            name='avg_altitude_min',
            field=models.FloatField(blank=True, help_text='Average minutes from takeoff to exit altitude (same-day only).', null=True),
        ),
        migrations.AlterField(
            model_name='dailyaircraftstats',
            name='avg_turn_min',
            field=models.FloatField(blank=True, help_text='Average minutes from landing to next takeoff (same-day only).', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyaircraftstats',
            unique_together={('aircraft', 'dropzone', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailyaircraftstats',
            index=models.Index(fields=['aircraft', '-date'], name='dz_dailyair_aircraf_47b3c9_idx'),
        ),
    ]
