# Generated by Django 5.2.6 on 2026-07-29 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz', '0004_daily_aircraft_stats_rolling_and_wind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTimeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overridden_call_time', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('load', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_time_override', to='dz.load')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_time_overrides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
