# Generated by Django 5.2.6 on 2025-09-16 19:06

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=50)),
                ('firmware_version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['device_id'], name='flights_fli_device__54d4d8_idx'), models.Index(fields=['session_id'], name='flights_fli_session_97f545_idx'), models.Index(fields=['created_at'], name='flights_fli_created_4300df_idx')],
                'unique_together': {('device_id', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='GPSPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitude_msl', models.FloatField()),
                ('velocity_north', models.FloatField()),
                ('velocity_east', models.FloatField()),
                ('velocity_down', models.FloatField()),
                ('horizontal_accuracy', models.FloatField()),
                ('vertical_accuracy', models.FloatField()),
                ('speed_accuracy', models.FloatField()),
                ('num_satellites', models.IntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='flights.flight')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='flights_gps_timesta_19a5a8_idx'), models.Index(fields=['flight', 'timestamp'], name='flights_gps_flight__3a53a3_idx'), django.contrib.postgres.indexes.GistIndex(fields=['location'], name='flights_gps_locatio_5e180d_gist')],
            },
        ),
    ]
