# Generated by Django 5.2.6 on 2025-09-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='analysis_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='analysis_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='analysis_version',
            field=models.CharField(default='enhanced_v1', max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='exit_altitude_agl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='flare_altitude_agl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='flare_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_swoop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='landing_altitude_agl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='landing_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='landing_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='max_ground_speed_mph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='max_ground_speed_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='max_gspeed_altitude_agl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='max_gspeed_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='max_vertical_speed_mph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='max_vertical_speed_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='max_vspeed_altitude_agl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='max_vspeed_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='rollout_end_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='rollout_start_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='rollout_time',
            field=models.FloatField(blank=True, help_text='Rollout time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='swoop_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='swoop_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='total_flight_time',
            field=models.FloatField(blank=True, help_text='Total flight time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='turn_direction',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='turn_rotation',
            field=models.FloatField(blank=True, help_text='Turn rotation in degrees', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='turn_time',
            field=models.FloatField(blank=True, help_text='Turn time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='gpspoint',
            name='altitude_agl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpspoint',
            name='ground_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpspoint',
            name='heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['is_swoop'], name='flights_fli_is_swoo_40c993_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['turn_rotation'], name='flights_fli_turn_ro_7acc80_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['max_vertical_speed_mph'], name='flights_fli_max_ver_5cf1ab_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['analysis_successful'], name='flights_fli_analysi_8ce8a3_idx'),
        ),
    ]
