# Generated by Django 5.2.6 on 2025-09-16 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_analysis_error_flight_analysis_successful_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flight',
            name='canopy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='users.canopy'),
        ),
        migrations.AddField(
            model_name='flight',
            name='location_name',
            field=models.CharField(blank=True, help_text='Drop zone or location name', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='notes',
            field=models.TextField(blank=True, help_text='Pilot notes about the jump'),
        ),
        migrations.AddField(
            model_name='flight',
            name='pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flight',
            name='weather_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('pilot', 'device_id', 'session_id')},
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['pilot'], name='flights_fli_pilot_i_ad2bef_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['pilot', 'created_at'], name='flights_fli_pilot_i_29f073_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['pilot', 'is_swoop'], name='flights_fli_pilot_i_f666d2_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['canopy'], name='flights_fli_canopy__4867ab_idx'),
        ),
    ]
