# Generated by Django 5.2.6 on 2025-09-17 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_options_alter_flight_unique_together_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='data_incorrect',
            field=models.BooleanField(default=False, help_text='Flag for flights with incorrect or problematic data'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['data_incorrect'], name='flights_fli_data_in_d7463c_idx'),
        ),
    ]
