# Generated by Django 5.2.6 on 2025-09-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_data_incorrect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='swoop_avg_horizontal_accuracy',
            field=models.FloatField(blank=True, help_text='Average hAcc during swoop in meters', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='swoop_avg_speed_accuracy',
            field=models.FloatField(blank=True, help_text='Average sAcc during swoop in m/s', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='swoop_avg_vertical_accuracy',
            field=models.FloatField(blank=True, help_text='Average vAcc during swoop in meters', null=True),
        ),
    ]
