# Generated by Django 5.2.6 on 2025-09-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flight_swoop_avg_horizontal_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpspoint',
            name='horizontal_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpspoint',
            name='speed_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpspoint',
            name='vertical_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
