# Generated by Django 5.2.6 on 2025-09-17 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_gpspoint_horizontal_accuracy_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['pilot', 'is_swoop', 'analysis_successful'], name='flights_fli_pilot_i_7a4480_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['max_ground_speed_mph'], name='flights_fli_max_gro_cf8e09_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['rollout_end_idx'], name='flights_fli_rollout_b7980c_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['landing_idx'], name='flights_fli_landing_422886_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['flare_idx'], name='flights_fli_flare_i_301217_idx'),
        ),
    ]
