# Generated by Django 5.2.6 on 2025-09-17 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_flight_flights_fli_pilot_i_7a4480_idx_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='swoop_distance_ft',
            field=models.FloatField(blank=True, help_text='Swoop distance from rollout end to landing in feet', null=True),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['swoop_distance_ft'], name='flights_fli_swoop_d_19be3f_idx'),
        ),
    ]
