# Generated by Django 5.2.6 on 2025-09-17 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_flight_swoop_distance_ft_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='swoop_avg_altitude_agl',
            field=models.FloatField(blank=True, help_text='Average altitude during swoop (flare to landing) in meters AGL', null=True),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['swoop_avg_altitude_agl'], name='flights_fli_swoop_a_011e66_idx'),
        ),
    ]
