# Generated by Django 5.2.6 on 2025-09-17 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_flight_swoop_avg_altitude_agl_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='gps_data_compressed',
            field=models.TextField(blank=True, help_text='Compressed JSON GPS data', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='gps_data_hash',
            field=models.CharField(blank=True, help_text='Hash of GPS data for integrity', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['gps_data_hash'], name='flights_fli_gps_dat_fea800_idx'),
        ),
    ]
