# Generated by Django 5.2.6 on 2025-09-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_flight_gps_data_compressed_flight_gps_data_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='entry_gate_speed_mph',
            field=models.FloatField(blank=True, help_text='Speed at entry gate (flare initiation) in mph', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='rollout_end_altitude_agl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='rollout_start_altitude_agl',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
