# Generated by Django 5.2.6 on 2025-09-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_flight_entry_gate_speed_mph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='entry_gate_speed_mps',
            field=models.FloatField(blank=True, help_text='Speed at entry gate (flare initiation) in m/s', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='swoop_distance_m',
            field=models.FloatField(blank=True, help_text='Swoop distance from rollout end to landing in meters', null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='entry_gate_speed_mph',
            field=models.FloatField(blank=True, help_text='Speed at entry gate (flare initiation) in mph (legacy)', null=True),
        ),
    ]
