# Generated by Django 5.2.6 on 2025-09-19 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_flight_entry_gate_speed_mps_flight_swoop_distance_m_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow others to view this flight'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['is_public'], name='flights_fli_is_publ_ba7584_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['pilot', 'is_public'], name='flights_fli_pilot_i_a924a4_idx'),
        ),
    ]
