# Generated by Django 5.2.6 on 2025-09-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_flight_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flare_detection_method',
            field=models.CharField(blank=True, choices=[('traditional', 'Traditional Flare'), ('turn_detection', 'Turn Detection Fallback')], help_text='Method used to detect the flare/turn initiation point', max_length=20, null=True),
        ),
    ]
