# Generated by Django 5.2.6 on 2025-09-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_add_flare_detection_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblematicFlight',
            fields=[
            ],
            options={
                'verbose_name': 'Problematic Flight',
                'verbose_name_plural': 'Problematic Flights',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flights.flight',),
        ),
        migrations.AddField(
            model_name='flight',
            name='intended_turn',
            field=models.IntegerField(blank=True, choices=[(90, '90°'), (270, '270°'), (450, '450°'), (630, '630°'), (810, '810°'), (990, '990°')], help_text='Intended standard turn degree classification', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='turn_rotation_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score for rotation calculation (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='turn_rotation_method',
            field=models.CharField(blank=True, help_text='Method used for rotation calculation (raw, smoothed, dominant, fallback)', max_length=20, null=True),
        ),
    ]
