# Generated by Django 5.2.6 on 2025-09-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0015_problematicflight_flight_intended_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='gswoop_difference',
            field=models.FloatField(blank=True, help_text='Difference from gswoop published rotation in degrees', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='turn_segment_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score for gswoop-style rotation (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='turn_segment_duration',
            field=models.FloatField(blank=True, help_text='Turn segment duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='turn_segment_end_alt',
            field=models.FloatField(blank=True, help_text='Turn segment end altitude in ft AGL', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='turn_segment_intended',
            field=models.IntegerField(blank=True, choices=[(90, '90°'), (270, '270°'), (450, '450°'), (630, '630°'), (810, '810°'), (990, '990°')], help_text='Intended turn classification for gswoop-style segment', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='turn_segment_method',
            field=models.CharField(blank=True, help_text='Method used for gswoop-style rotation calculation', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='turn_segment_rotation',
            field=models.FloatField(blank=True, help_text='gswoop-style turn segment rotation in degrees', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='turn_segment_start_alt',
            field=models.FloatField(blank=True, help_text='Turn segment start altitude in ft AGL', null=True),
        ),
    ]
