# Generated by Django 5.2.6 on 2025-09-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0016_flight_gswoop_difference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='ml_intended_turn',
            field=models.IntegerField(blank=True, choices=[(90, '90°'), (270, '270°'), (450, '450°'), (630, '630°'), (810, '810°'), (990, '990°')], help_text='ML-predicted intended turn classification', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_rotation',
            field=models.FloatField(blank=True, help_text='ML-predicted rotation in degrees', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_rotation_confidence',
            field=models.FloatField(blank=True, help_text='ML prediction confidence (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_rotation_method',
            field=models.CharField(blank=True, help_text='ML prediction method (ml_enhanced, fallback)', max_length=20, null=True),
        ),
    ]
