# Generated by Django 5.2.6 on 2025-10-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_flight_ml_intended_turn_flight_ml_rotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='ml_distance_confidence',
            field=models.FloatField(blank=True, help_text='Distance prediction confidence', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_distance_to_stop',
            field=models.FloatField(blank=True, help_text='ML-predicted distance to stop (feet)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_entry_speed',
            field=models.FloatField(blank=True, help_text='ML-predicted entry gate speed (mph)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_entry_speed_confidence',
            field=models.FloatField(blank=True, help_text='Entry speed prediction confidence', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_predictions_count',
            field=models.IntegerField(blank=True, help_text='Number of ML predictions available', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_predictions_updated_at',
            field=models.DateTimeField(blank=True, help_text='When ML predictions were last updated', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_rollout_time',
            field=models.FloatField(blank=True, help_text='ML-predicted rollout duration (seconds)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_rollout_time_confidence',
            field=models.FloatField(blank=True, help_text='Rollout time prediction confidence', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_swoop_time',
            field=models.FloatField(blank=True, help_text='ML-predicted time aloft during swoop (seconds)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_swoop_time_confidence',
            field=models.FloatField(blank=True, help_text='Swoop time prediction confidence', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_touchdown_confidence',
            field=models.FloatField(blank=True, help_text='Touchdown distance prediction confidence', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_touchdown_distance',
            field=models.FloatField(blank=True, help_text='ML-predicted touchdown distance (feet)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_touchdown_speed',
            field=models.FloatField(blank=True, help_text='ML-predicted touchdown speed (mph)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_touchdown_speed_confidence',
            field=models.FloatField(blank=True, help_text='Touchdown speed prediction confidence', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_turn_init_back',
            field=models.FloatField(blank=True, help_text='ML-predicted turn initiation back position (feet)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_turn_init_offset',
            field=models.FloatField(blank=True, help_text='ML-predicted turn initiation offset position (feet)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_turn_time',
            field=models.FloatField(blank=True, help_text='ML-predicted time to execute turn (seconds)', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='ml_turn_time_confidence',
            field=models.FloatField(blank=True, help_text='Turn time prediction confidence', null=True),
        ),
    ]
