# Generated by Django 5.2.6 on 2025-10-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0018_add_multi_metric_ml_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_name',
            field=models.CharField(blank=True, help_text='User-friendly flight name', max_length=255),
        ),
    ]
