# Generated by Django 5.2.6 on 2025-10-11 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0019_add_flight_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the competition location or event', max_length=200)),
                ('gate_type', models.CharField(choices=[('standard', 'Standard Gates (Distance/Zone Accuracy)'), ('speed', 'Speed Gates')], help_text='Type of gates', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gate_file', models.FileField(help_text='Upload .gsw or .CSV gate file', upload_to='gate_files/')),
                ('gate_positions', models.JSONField(blank=True, help_text='Parsed gate positions with lat/lon/altitude', null=True)),
                ('course_config', models.JSONField(blank=True, help_text='Complete course geometry based on USPA rules', null=True)),
                ('center_lat', models.FloatField(blank=True, help_text='Center latitude for map display', null=True)),
                ('center_lon', models.FloatField(blank=True, help_text='Center longitude for map display', null=True)),
                ('is_parsed', models.BooleanField(default=False, help_text='Whether the gate file has been successfully parsed')),
                ('parse_error', models.TextField(blank=True, help_text='Error message if parsing failed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_gates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gate_type'], name='flights_com_gate_ty_054a36_idx'), models.Index(fields=['created_by'], name='flights_com_created_e4696d_idx'), models.Index(fields=['is_parsed'], name='flights_com_is_pars_a43d19_idx')],
            },
        ),
    ]
