# Generated by Django 5.2.6 on 2025-10-11 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0020_competitiongate'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='competition_gate',
            field=models.ForeignKey(blank=True, help_text='Competition gate/course for this flight', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='flights.competitiongate'),
        ),
        migrations.AddField(
            model_name='flight',
            name='gate_altitude_agl',
            field=models.FloatField(blank=True, help_text='Altitude at gate crossing in meters AGL', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='gate_crossing_idx',
            field=models.IntegerField(blank=True, help_text='Index where flight crossed entry gates', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='gate_speed_mps',
            field=models.FloatField(blank=True, help_text='Speed at gate crossing in m/s', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='passed_between_gates',
            field=models.BooleanField(blank=True, help_text='Whether flight passed cleanly between gates', null=True),
        ),
    ]
