# Generated by Django 5.2.6 on 2026-09-16 23:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('distance', 'Drag Distance'), ('speed', 'Carved Speed'), ('accuracy', 'Zone Accuracy')], max_length=10)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.FileField(upload_to='course_imports/')),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('format', models.CharField(choices=[('kml', 'KML'), ('survey_csv', 'Survey CSV/GSW')], max_length=20)),
                ('input_mode', models.CharField(choices=[('explicit_geometry', 'Explicit geometry'), ('g1_seed', 'G1 seed + heading'), ('survey', 'gSwoop-style survey')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preview_ready', 'Preview ready'), ('committed', 'Committed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('validation_report', models.JSONField(blank=True, default=dict, help_text='Warnings/errors from parsing')),
                ('extracted', models.JSONField(blank=True, help_text='Preview data: detected entry setup(s) and per-discipline geometry candidates', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('geometry', models.JSONField(help_text='Discipline geometry dict as produced by courses.geometry')),
                ('geometry_hash', models.CharField(editable=False, max_length=64)),
                ('algorithm_version', models.CharField(blank=True, max_length=50)),
                ('g1_lon', models.FloatField()),
                ('g1_lat', models.FloatField()),
                ('entry_heading_deg_true', models.FloatField()),
                ('course_width_m', models.FloatField()),
                ('carve_direction', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='G1 center, for location filtering', null=True, srid=4326)),
                ('source', models.CharField(choices=[('generated_from_g1', 'Generated from G1 seed'), ('kml_explicit', 'Explicit KML geometry'), ('kml_seed', 'KML G1 seed'), ('survey', 'gSwoop-style survey')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='courses.courseimport')),
            ],
            options={
                'ordering': ['course', '-revision_number'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.courserevision'),
        ),
        migrations.CreateModel(
            name='CourseSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('site_name', models.CharField(blank=True, help_text='Dropzone or location name, free text for now', max_length=200)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('manage_all_courses', 'Can view, edit, and moderate all course sets')],
            },
        ),
        migrations.AddField(
            model_name='courseimport',
            name='committed_course_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='courses.courseset'),
        ),
        migrations.CreateModel(
            name='CourseAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('course_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='courses.courseset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.courseset'),
        ),
        migrations.AddConstraint(
            model_name='courserevision',
            constraint=models.UniqueConstraint(fields=('course', 'revision_number'), name='unique_revision_number_per_course'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_set', 'discipline'), name='unique_discipline_per_course_set'),
        ),
    ]
