# Generated by Django 5.2.6 on 2026-09-17 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('flights', '0024_flight_canopy_start_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCourseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_version', models.CharField(max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('window_start_idx', models.IntegerField(blank=True, null=True)),
                ('window_end_idx', models.IntegerField(blank=True, null=True)),
                ('entry_status', models.CharField(choices=[('crossed', 'Crossed'), ('not_crossed', 'Not crossed'), ('entry_not_detected', 'Entry not detected')], max_length=20)),
                ('gate_results', models.JSONField(default=dict, help_text='gate_id -> serialized GateCrossingResult')),
                ('metrics', models.JSONField(default=dict, help_text='Discipline-specific derived metrics')),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_analyses', to='courses.course')),
                ('course_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_analyses', to='courses.courserevision')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_analyses', to='flights.flight')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flight', 'is_primary'], name='courses_fli_flight__5a5e9f_idx')],
            },
        ),
    ]
