# Generated by Django 5.2.6 on 2026-09-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_flightcourseanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcourseanalysis',
            name='avg_vertical_accuracy_m',
            field=models.FloatField(blank=True, help_text='Mean receiver-reported vertical accuracy (vAcc) over the analyzed window; a quality indicator, not a verified error bound on any specific result', null=True),
        ),
    ]
