from django.urls import path
from . import views

urlpatterns = [
    path('', views.jump_list, name='jump_list'),
    path('log/', views.log_jumps, name='log_jumps'),
    path('upload/', views.upload_wizard_step1, name='logbook_upload'),
    path('upload/log/', views.upload_wizard_step2, name='logbook_upload_log'),
    path('import/', views.import_csv_step1, name='logbook_import'),
    path('import/map/', views.import_csv_step2, name='logbook_import_map'),
    path('import/confirm/', views.import_csv_confirm, name='logbook_import_confirm'),
    path('<int:pk>/edit/', views.edit_jump, name='edit_jump'),
    path('<int:pk>/delete/', views.delete_jump, name='delete_jump'),
    path('<int:pk>/attach-gps/', views.attach_gps, name='attach_gps'),
    path('<int:pk>/link-flight/', views.link_flight, name='link_flight'),
    path('<int:pk>/unlink-flight/', views.unlink_flight, name='unlink_flight'),
    path('<int:pk>/link-slot/', views.link_slot, name='link_slot'),
    path('<int:pk>/unlink-slot/', views.unlink_slot, name='unlink_slot'),
    path('bulk-delete/', views.bulk_delete_jumps, name='bulk_delete_jumps'),
    path('query/', views.query_view, name='logbook_query'),
    path('query/save/', views.save_query, name='logbook_query_save'),
    path('query/<int:pk>/delete/', views.delete_query, name='logbook_query_delete'),
    path('query/<int:pk>/load/', views.load_query, name='logbook_query_load'),
    path('query/<int:pk>/widget/', views.toggle_widget, name='logbook_query_toggle_widget'),
    path('earnings/', views.instructor_earnings_view, name='instructor_earnings'),
    # Student ISP sign-off
    path('student/', views.student_hub, name='student_hub'),
    path('student/progress/', views.student_progress, name='student_progress'),
    path('student/instructor-search/', views.instructor_search, name='instructor_search'),
    path('<int:pk>/request-signoff/', views.request_signoff, name='request_signoff'),
    path('<int:pk>/signoff/', views.view_signoff, name='view_signoff'),
    path('instructor/', views.instructor_hub, name='instructor_hub'),
    path('instructor/queue/', views.instructor_queue, name='instructor_queue'),
    path('instructor/sign/<int:pk>/', views.signoff_form, name='signoff_form'),
]
