# Generated by Django 5.2.6 on 2026-03-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jump',
            new_name='logbook_jum_user_id_b97fa1_idx',
            old_name='logbook_jum_user_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='jump',
            new_name='logbook_jum_user_id_e3424a_idx',
            old_name='logbook_jum_user_id_num_idx',
        ),
        migrations.RenameIndex(
            model_name='jump',
            new_name='logbook_jum_user_id_0f7ab0_idx',
            old_name='logbook_jum_user_id_swoop_idx',
        ),
        migrations.RenameIndex(
            model_name='jump',
            new_name='logbook_jum_flight__ad13b9_idx',
            old_name='logbook_jum_flight_idx',
        ),
    ]
