# Generated by Django 5.2.6 on 2026-03-30 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_instructorrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jump',
            name='student_category',
            field=models.CharField(blank=True, choices=[('a', 'Category A'), ('b', 'Category B'), ('c', 'Category C'), ('d', 'Category D'), ('e', 'Category E'), ('f', 'Category F'), ('g', 'Category G'), ('h', 'Category H')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='jump',
            name='student_jump_method',
            field=models.CharField(blank=True, choices=[('AFF', 'AFF'), ('Tandem', 'Tandem'), ('IAD_SL', 'IAD / Static Line'), ('Coach', 'Coach')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='StudentSignoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('instructor_name', models.CharField(max_length=100)),
                ('instructor_license', models.CharField(blank=True, max_length=20)),
                ('instructor_rating', models.CharField(choices=[('AFF-I', 'AFF Instructor'), ('TI', 'Tandem Instructor'), ('IAD-I', 'IAD/Static Line Instructor'), ('Coach', 'Coach')], max_length=10)),
                ('criteria_passed', models.JSONField(default=dict, help_text='{"ground": [...], "freefall": [...], "canopy": [...], "method": [...]}')),
                ('criteria_modified', models.BooleanField(default=False, help_text="True if the instructor changed the student's pre-filled criteria")),
                ('student_notified', models.BooleanField(default=False)),
                ('jump', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_signoff', to='logbook.jump')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_signoffs_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingInstructorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_criteria', models.JSONField(default=dict, help_text='{"ground": [...], "freefall": [...], "canopy": [...], "method": [...]}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_sign_requests', to=settings.AUTH_USER_MODEL)),
                ('jump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_instructor_requests', to='logbook.jump')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('jump', 'instructor')},
            },
        ),
    ]
