# Generated by Django 5.2.6 on 2026-07-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_savedquery_widget_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jump',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jump',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
