# Generated by Django 5.2.6 on 2026-06-10 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_savedquery_widget_fields'),
        ('training', '0003_training_progression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programjump',
            name='allowed_methods',
            field=models.JSONField(default=list, help_text='Specific jump methods valid for this jump, e.g. ["AFF_2I", "AFF_solo"]'),
        ),
        migrations.AlterField(
            model_name='programjump',
            name='assigned_criteria',
            field=models.JSONField(default=dict, help_text='Criteria from the category pool evaluated on this jump: {"ground": [...], ...}'),
        ),
        migrations.AlterField(
            model_name='programjump',
            name='dive_flow',
            field=models.JSONField(default=list, help_text='Ordered sequence of maneuvers/actions for this jump, from the SIM'),
        ),
        migrations.AlterField(
            model_name='programjump',
            name='jump_number',
            field=models.PositiveIntegerField(help_text='Ordering within the category + method group at this DZ (1, 2, …)'),
        ),
        migrations.AlterField(
            model_name='programjump',
            name='method_group',
            field=models.CharField(choices=[('all', 'All Methods'), ('AFF_Tandem', 'AFF / Tandem'), ('AFF', 'AFF Only'), ('Tandem', 'Tandem Only'), ('IAD_SL', 'IAD / Static Line'), ('Coach', 'Coach')], default='all', help_text='Which training pathway this jump belongs to within the category', max_length=20),
        ),
        migrations.AlterField(
            model_name='programjump',
            name='name',
            field=models.CharField(blank=True, help_text='Optional label, e.g. "90° Turns", "Clear & Pull"', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='current_jump',
            field=models.ForeignKey(blank=True, help_text='The specific DZ program jump the student is currently working on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_at_jump', to='training.programjump'),
        ),
        migrations.AlterField(
            model_name='studentjump',
            name='criteria_passed',
            field=models.JSONField(default=dict, help_text='{"ground": [...], "freefall": [...], "canopy": [...]}'),
        ),
        migrations.AlterField(
            model_name='studentjump',
            name='jump',
            field=models.OneToOneField(blank=True, help_text="Link to the student's personal logbook entry, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_jump', to='logbook.jump'),
        ),
        migrations.AlterField(
            model_name='studentjump',
            name='outcome',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('repeat', 'Repeat'), ('partial', 'Partial Pass'), ('incomplete', 'Incomplete')], help_text='Set when the instructor completes the debrief', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uspacategory',
            name='criteria',
            field=models.JSONField(default=dict, help_text='Full criteria pool: {"ground": [...], "freefall": [...], "canopy": [...], "AFF": [...]}'),
        ),
        migrations.AlterField(
            model_name='uspacategory',
            name='name',
            field=models.CharField(help_text="e.g. 'First Jump Course', 'Category A'", max_length=50),
        ),
        migrations.AlterField(
            model_name='uspacategory',
            name='order',
            field=models.PositiveIntegerField(help_text='Sort order within program type'),
        ),
        migrations.AlterField(
            model_name='uspacategory',
            name='recommended_jumps',
            field=models.JSONField(default=dict, help_text="USPA-recommended jump structure keyed by method group. Each entry is a list of jump definitions with dive_flow and allowed_methods. Used by setup_dz_program to seed a DZ's default structure."),
        ),
    ]
