# Generated by Django 5.2.6 on 2026-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_programjump_allowed_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentjump',
            name='e_signature_data',
            field=models.JSONField(blank=True, default=dict, help_text='Captured signature metadata: typed name, timestamp, IP address.'),
        ),
    ]
